name: 'Test YAML'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*-echelon'

permissions:
  contents: read
  pull-requests: read

jobs:
  linux-ubuntu_test:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
          fetch-tags: 'true'

      - name: 'HT'
        run: 'echo Hello, Test!'

      - name: 'Git Show'
        run: 'git show'
