name: 'Test YAML'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*-echelon'

permissions:
  contents: read
  pull-requests: read

jobs:
  linux-ubuntu_test:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: '3'
      # START: Workaround bug (Fetch Tags)
      #   Problem: actions/checkout@v4 with [fetch-tags: 'true'] fails when triggered by tag create/push event.
      #   Solution: Use a separate and subsequent tag fetch step
          #fetch-tags: 'true'
          fetch-tags: 'false'

      # Now we can fetch the tags
      - name: 'Fetch Tags'
        run: 'git fetch --tags'
      # END: Workaround bug (Fetch Tags)

      - name: 'HT'
        run: 'echo Hello, Test!'

      - name: 'Git Show'
        run: 'git show'
